### ISSUE TITLE
cdk installation issue

### ISSUE THREAD

**Issue by josiahdavis** [aws-samples/lambdamap#10]
## I'm having an issue installing the aws cdk following the instructions.

Here is the full error when I run `cdk boostrap`:

```
/Users/davjosia/miniconda3/envs/lambdamap/lib/node_modules/aws-cdk/bin/cdk.js:25
async function parseCommandLineArguments() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/davjosia/miniconda3/envs/lambdamap/lib/node_modules/aws-cdk/bin/cdk:2:1)
```

## Steps to reproduce

```
conda create -y -n lambdamap python=3.8
conda activate lambdamap
conda install -c conda-forge nodejs
npm i -g aws-cdk

git clone https://github.com/aws-samples/lambdamap.git
cd lambdamap/lambdamap_cdk
pip3 install -r requirements.txt
cdk bootstrap
```

## System Information

* Node: v6.13.1
* npm: 3.10.10
* Python: 3.8.11
* Mac OS

**Comment by josiahdavis** [comment]
## Issue

The issue I discovered is that conda-forge resorts to an older node version that appears to be incompatible with the cdk.

## Solution

When I install nodejs in the same step as the environment creation I am able to get a newer version of node (i.e., v16.6.1) and the cdk installs correctly.

So this:

```
conda create -n lambdamap python=3.8
conda activate lambdamap
conda install -c conda-forge nodejs
```

becomes this:

```
conda create -n lambdamap -c conda-forge nodejs python=3.8
conda activate lambdamap
```

**Comment by josiahdavis** [comment]
References: 
* https://stackoverflow.com/questions/62325068/cannot-install-latest-nodejs-using-conda-on-mac
* https://github.com/aws/aws-cdk/issues/808
